### ISSUE TITLE
Stuck 

### ISSUE THREAD

**Issue by qadir-genetech** [yonilevy/noiseclean#2]
I tried like this
$ sh noiseclean.sh babble.wav babble_clean.wav 

but here is the output and is stuck

noiseclean.sh: line 32: ffprobe: command not found
Detected 'babble.wav' as an audio file
Sample noise start time [00:00:00]:

**Comment by yonilevy** [comment]
Yeah this script requires that you have both [ffmpeg](http://sox.sourceforge.net/) and [sox](http://sox.sourceforge.net/) installed, I'll edit the readme to reflect that.

Thanks for reporting!
